version: 1.0.{build}
skip_tags: true
configuration: Release
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: mqfd5QXj3a2N+D2EP9avxupQJRBJFEKT9kjF7Tipl1OCkUvPBsKjfiZMQHpnwVKq
  on:
    branch: master
notifications:
  - provider: Slack
    auth_token:
      secure: xLrYwFJVzehV+sdSJsDp52X1TSPeSGJrr56LI2GQDvrmkpjcrwX1rmPwdH+i14H8lijQDcWbUt9jl81saehgRA==
    channel: '#build'